[package]
name = "latex-rs_tectonic_together"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
latex = "0.3.1"
tectonic = { version = "0.14.1", features = ["external-harfbuzz"] }
